sudo: required
dist: trusty
language: node_js

node_js:
  - "stable"
  - "10"
  - "8"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

script:
  - npm run lint
  - npm run coverage

after_script:
  - cat ./coverage/lcov.info | coveralls
